= Model order reduction and sensitivity analysis for complex heat transfer simulations inside the human eyeball
Thomas Saigre, Christophe Prud'homme, Marcela Szopos
:!figure-caption:
:version: v1.0.0
:stem: latexmath

[.author]
Thomas Saigre::
Cemosis, Institut de Recherche Mathématique Avancée, UMR 7501 Université de Strasbourg - CNRS. +
email: thomas.saigre@math.unistra.fr


[.author]
Christophe Prud'homme::
Cemosis, Institut de Recherche Mathématique Avancée, UMR 7501 Université de Strasbourg - CNRS. +
email: christophe.prudhomme@cemosis.fr

[.author]
Marcela Szopos::
Université Paris Cité, CNRS, MAP5, F-75006 Paris, France. +
email: marcela.szopos@u-paris.fr


.Article DOI
--
image:https://img.shields.io/badge/10.1002/cnm.3864-Model%20order%20reduction%20and%20sensitivity%20analysis%20for%20complex%20heat%20transfer%20simulations%20inside%20the%20human%20eyeball-blue[DOI,link=https://doi.org/10.1002/cnm.3864]
--

.Repository and Dataset Zenodo DOI
--

--

.GitHub Information
--
image:https://img.shields.io/github/v/release/feelpp/article.eye-heat-fom-rom-sa.ijnmbe24[GitHub Release]
image:https://img.shields.io/github/actions/workflow/status/feelpp/article.eye-heat-fom-rom-sa.ijnmbe24/latex.yml[GitHub Actions Workflow Status]
image:https://img.shields.io/github/downloads/feelpp/article.eye-heat-fom-rom-sa.ijnmbe24/total[GitHub Downloads (all assets, all releases)]
--

== Abstract

Heat transfer in the human eyeball, a complex organ, is significantly influenced by various pathophysiological and external parameters.
Particularly, heat transfer critically affects fluid behavior within the eye and ocular drug delivery processes.
Overcoming the challenges of experimental analysis, this study introduces a comprehensive three-dimensional mathematical and computational model to simulate the heat transfer in a realistic geometry.
Our work includes an extensive sensitivity analysis to address uncertainties and delineate the impact of different variables on heat distribution in ocular tissues.
To manage the model's complexity, we employed a very fast model reduction technique with certified sharp error bounds, ensuring computational efficiency without compromising accuracy.
Our results demonstrate remarkable consistency with experimental observations and align closely with existing numerical findings in the literature.
Crucially, our findings underscore the significant role of blood flow and environmental conditions, particularly in the eye's internal tissues.
Clinically, this model offers a promising tool for examining the temperature-related effects of various therapeutic interventions on the eye.
Such insights are invaluable for optimizing treatment strategies in ophthalmology.


== How to cite

If you want to refer to the article, please cite it as follows:

.Chicago style
[source]
----
Saigre, T., Prud'homme, C., & Szopos, M. (2024). Model order reduction and sensitivity analysis for complex heat transfer simulations inside the human eyeball. International Journal for Numerical Methods in Biomedical Engineering. https://doi.org/10.1002/cnm.3864
----

.BibTeX
[source,bibtex]
----
@article{Saigre_Model_order_reduction_2024,
author = {Saigre, Thomas and Prud'homme, Christophe and Szopos, Marcela},
doi = {10.1002/cnm.3864},
journal = {International Journal for Numerical Methods in Biomedical Engineering},
month = sep,
title = {{Model order reduction and sensitivity analysis for complex heat transfer simulations inside the human eyeball}},
year = {2024}
}
----

== How to reproduce the results

The dataset is available in `data/`.

The meshes construction are available in https://github.com/feelpp/mesh.eye. <<mesh>>
Insert the meshes in the directory `data/mesh`.



=== Run the high fidelity model

The high fidelity model is run using the Feel++ <<feelpp>> heat tooblox <<heat>>:

[source, bash]
----
[mpirun -np 12] feelpp_toolbox_heat --config-file eye.cfg
----

The previous command line runs the linearized model $\mathcal{E}_\text{L}(\mu)$. To run the nonlinear model $\mathcal{E}_\text{NL}(\mu)$, use the configuration file `eye-full.cfg`.

To change the parameters of the model, update the content of the section `Parameters` in the file link:data/eye.json[`eye.json`].

To use another mesh, update the content of the section `Meshes/heat/Import` in the file link:data/mesh3d.json[`mesh3d.json`].

NOTE: When running in parallel, make sure that the mesh is partitioned correctly. In the JSON file, the macro `$np` will be replaced by the number of MPI processes.


=== Run the deterministic sensitivity analysis

To reproduce the results of the deterministic sensitivity analysis, presented in section 4.1 of the pulication, run

[source, bash]
----
[mpirun -np 12] python3 run-SA.py
----


=== Generate the reduced basis metamodel, and run de stochastic sensitivity analysis

To reproduce the results of the reduced basis model presented in Section 3.3 of the publication, and the results of the stochastic sensitivity analysis presented in Section 4.2, refer to the code integrated to the Feel++ repository <<feelpp>>, in the directory https://github.com/feelpp/feelpp/tree/develop/mor/examples/eye2brain[`feelpp/mor/examples/eye2brain`].


== References

* [[mesh]] Chabannes, V., Prud'homme, C., Saigre, T., Lorenzo, S., Szopos, M., & Trophime, C. (2024). A 3D geometrical model and meshing procedures for the human eyeball (Version 1.0.0) [Computer software]. https://github.com/feelpp/mesh.eye image:https://zenodo.org/badge/DOI/10.5281/zenodo.13886143.svg[DOI,link=https://github.com/feelpp/mesh.eye]
* [[feelpp]] Christophe Prud'homme, Vincent Chabannes, Thomas Saigre, Christophe Trophime, Luca Berti, Abdoulaye Samaké, Céline Van Landeghem, et al. « Feelpp/feelpp: Feel++ Release V111 Preview.10 ». Zenodo, 15 juillet 2024. . image:https://zenodo.org/badge/DOI/10.5281/zenodo.12742155.svg[DOI,link=https://doi.org/10.5281/zenodo.12742155]
* [[heat]] "Heat Transfer Toolbox Application Manual." Feel++ Documentation, 2024, https://docs.feelpp.org/toolboxes/latest/heat/index.html.

== Acknowledgements

We would like to thank C. Trophime from LNCMI, V. Chabannes from Cemosis for their support and fruitful discussions.

