= Model order reduction and sensitivity analysis for complex heat transfer simulations inside the human eyeball
Thomas Saigre, Christophe Prud'homme, Marcela Szopos
:!figure-caption:
:version: v1.0.0
:stem: latexmath

[.author]
Thomas Saigre::
Cemosis, Institut de Recherche Mathématique Avancée, UMR 7501 Université de Strasbourg - CNRS
email: thomas.saigre@math.unistra.fr


[.author]
Christophe Prud'homme::
Cemosis, Institut de Recherche Mathématique Avancée, UMR 7501 Université de Strasbourg - CNRS
email: christophe.prudhomme@cemosis.fr

[.author]
Marcela Szopos::
Université Paris Cité, CNRS, MAP5, F-75006 Paris, France
email: marcela.szopos@u-paris.fr


.Article DOI
--
image:https://img.shields.io/badge/10.1002/cnm.3864-Model%20order%20reduction%20and%20sensitivity%20analysis%20for%20complex%20heat%20transfer%20simulations%20inside%20the%20human%20eyeball-blue[DOI,link=https://doi.org/10.1002/cnm.3864]
--

.Repository and Dataset Zenodo DOI 
--

--

.GitHub Information
--
image:https://img.shields.io/github/v/release/feelpp/article.eye-heat-fom-rom-sa.ijnmbe24[GitHub Release]
image:https://img.shields.io/github/actions/workflow/status/feelpp/article.eye-heat-fom-rom-sa.ijnmbe24/latex.yml[GitHub Actions Workflow Status]
image:https://img.shields.io/github/downloads/feelpp/article.eye-heat-fom-rom-sa.ijnmbe24/total[GitHub Downloads (all assets, all releases)]
--

== Abstract

Heat transfer in the human eyeball, a complex organ, is significantly influenced by various pathophysiological and external parameters.
Particularly, heat transfer critically affects fluid behavior within the eye and ocular drug delivery processes.
Overcoming the challenges of experimental analysis, this study introduces a comprehensive three-dimensional mathematical and computational model to simulate the heat transfer in a realistic geometry.
Our work includes an extensive sensitivity analysis to address uncertainties and delineate the impact of different variables on heat distribution in ocular tissues.
To manage the model's complexity, we employed a very fast model reduction technique with certified sharp error bounds, ensuring computational efficiency without compromising accuracy.
Our results demonstrate remarkable consistency with experimental observations and align closely with existing numerical findings in the literature.
Crucially, our findings underscore the significant role of blood flow and environmental conditions, particularly in the eye's internal tissues.
Clinically, this model offers a promising tool for examining the temperature-related effects of various therapeutic interventions on the eye.
Such insights are invaluable for optimizing treatment strategies in ophthalmology.


== How to cite

If you want to refer to the article, please cite it as follows:

.Chicago style
[source]
----
Saigre, T., Prud'homme, C., & Szopos, M. (2024). Model order reduction and sensitivity analysis for complex heat transfer simulations inside the human eyeball. International Journal for Numerical Methods in Biomedical Engineering. https://doi.org/10.1002/cnm.3864
----

.BibTeX
[source,bibtex]
----
@article{Saigre_Model_order_reduction_2024,
author = {Saigre, Thomas and Prud'homme, Christophe and Szopos, Marcela},
doi = {10.1002/cnm.3864},
journal = {International Journal for Numerical Methods in Biomedical Engineering},
month = sep,
title = {{Model order reduction and sensitivity analysis for complex heat transfer simulations inside the human eyeball}},
year = {2024}
}
----
